// this is an autogenerated file -- don't try to edit it!
#ifndef AGHFILE_H
#define AGHFILE_H

#pragma once

#include <string>

#include "agh.h"
#include "asset.h"

using std::vector;

vector<asset> assetSet = {
    asset(ASSET::FONT, "YKLIGHT", __data_font_yklight_otf, __data_font_yklight_otf_len),

};
#endif  // AGHFILE_H
